# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

add_newline = false

command_timeout = 1000

format = """\
$os\
$username\
$hostname\
$directory\
$character\
"""

right_format = """\
$cmd_duration\
$jobs\
$time\
$all\
"""

####### LHS

# OS symbols
[os]
format = '[$symbol](bold flamingo)  '   
disabled = false

[os.symbols]
Windows = ''
EndeavourOS = ''
Ubuntu = ''
Macos = '󰀵'

# Username options
[username]
style_user = 'mauve bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

#
[hostname]
ssh_only = false
ssh_symbol = '󰣀 '
style = 'bold lavender'
format = 'on [$ssh_symbol$hostname]($style) '
disabled = false

# very read-only directories
[directory]
home_symbol = '󰋜 '
read_only_style = '#ff0000'
read_only = '  '
style = 'bold teal'
format = 'at [$path]($style)[$read_only]($read_only_style) '

# uniform prompt characters
[character]
success_symbol = '[❯](bold #00ff00)'
error_symbol = ''
format = '[$symbol](style) '

####### RHS

[cmd_duration]
format = "[took $duration]($style) "
style = "bold yellow"

[jobs]
symbol = ""
style = "#ff0000"
number_threshold = 1
format = "[$symbol]($style) "

[time]
disabled = false
style = "bold white"
format = "[$time]($style) "

[status]
symbol = '[󰚌](#ff0000)'
success_symbol = '[](#00ff00)'
format = '$symbol '
disabled = false

# Colors
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"